### PR TITLE
Add linux support

### LINKED ISSUE #7: Support Linux
This depends on Swift becoming available for Linux.

### PR DESCRIPTION
**Pull request by kylef**
Closes #7

### CODE REVIEW

**Comment by kylef** [comment]
It now compiles, but unfortunately a problem finding the dynamic libraries when running:

```
$ ./bin/conche
./bin/conche: error while loading shared libraries: libCommander.so: cannot open shared object file: No such file or directory
```

**Comment by kattrali** [comment]
Very odd error

**Comment by kylef** [comment]
@kattrali It's because .conche/lib isn't in library search paths. I can probably make `conche exec` do this, just requires you have an installed version of conche.

**Comment by kylef** [comment]
Closing out this issue as Conche is deprecated for the Swift Package Manager (SPM). Instead you can use SPM (https://github.com/Conche/Conche/commit/78708a9556b00d602de4c3e518a7f201b55a519b).

**Pull request closed without merging**
